name = "axint-registry"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
GITHUB_CLIENT_ID = "Ov23lip5Gwm9SHRhSR2a"

[[d1_databases]]
binding = "DB"
database_name = "axint-registry"
database_id = "14155d9c-09d2-4020-a6c4-ce9828022c2d"

[[r2_buckets]]
binding = "PACKAGES"
bucket_name = "axint-packages"

[[routes]]
pattern = "registry.axint.ai"
custom_domain = true
