"""
Native Python Swift code generator.

Produces the exact same Swift output as the TypeScript generator in
`src/core/generator.ts`. This eliminates the Node.js dependency — the
Python SDK can now compile Python intent files to Swift without shelling
out to `@axintai/compiler`.

The generator is deliberately kept in lock-step with the TS version:
same struct layout, same decorator style, same return-type signatures.
If you change one, change the other.
"""

from __future__ import annotations

from .ir import IntentIR, IntentParameter

# ── Swift Type Mapping ──────────────────────────────────────────────

SWIFT_TYPE_MAP: dict[str, str] = {
    "string": "String",
    "int": "Int",
    "double": "Double",
    "float": "Float",
    "number": "Int",  # legacy alias
    "boolean": "Bool",
    "date": "Date",
    "duration": "Measurement<UnitDuration>",
    "url": "URL",
}

DEFAULT_LITERALS: dict[str, str] = {
    "string": '""',
    "int": "0",
    "double": "0.0",
    "float": "Float(0)",
    "number": "0",
    "boolean": "false",
    "date": "Date()",
    "duration": "Measurement<UnitDuration>(value: 0, unit: .seconds)",
    "url": 'URL(string: "about:blank")!',
}


# ── String Escaping ─────────────────────────────────────────────────

def escape_swift_string(s: str) -> str:
    """Escape a string for safe interpolation into Swift string literals."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def escape_xml(s: str) -> str:
    """Escape a string for safe interpolation into XML (plist)."""
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


# ── Primary Swift Generator ─────────────────────────────────────────

def generate_swift(intent: IntentIR) -> str:
    """Generate a Swift App Intent source file from an IntentIR."""
    lines: list[str] = []

    # File header
    lines.append(f"// {intent.name}Intent.swift")
    lines.append("// Generated by Axint — https://github.com/agenticempire/axint")
    lines.append("// Do not edit manually. Re-run `axint compile` to regenerate.")
    lines.append("")
    lines.append("import AppIntents")
    lines.append("import Foundation")
    lines.append("")

    # Struct declaration
    lines.append(f"struct {intent.name}Intent: AppIntent {{")

    # Static metadata
    lines.append(
        f'    static let title: LocalizedStringResource = "{escape_swift_string(intent.title)}"'
    )
    lines.append(
        f'    static let description: IntentDescription = IntentDescription("{escape_swift_string(intent.description)}")'
    )
    lines.append(f"    static let isDiscoverable: Bool = {str(intent.is_discoverable).lower()}")
    lines.append("")

    # Parameters
    for param in intent.parameters:
        lines.append(_generate_parameter(param))

    if intent.parameters:
        lines.append("")

    # Perform function
    return_type = intent.return_type or "string"
    swift_return = SWIFT_TYPE_MAP.get(return_type, "String")
    return_sig = f"some IntentResult & ReturnsValue<{swift_return}>"

    lines.append(f"    func perform() async throws -> {return_sig} {{")
    lines.append("        // TODO: Implement your intent logic here.")

    if intent.parameters:
        param_list = ", ".join(f"\\({p.name})" for p in intent.parameters)
        lines.append(f"        // Parameters available: {param_list}")

    default_literal = DEFAULT_LITERALS.get(return_type, '""')
    lines.append(f"        return .result(value: {default_literal})")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def _generate_parameter(param: IntentParameter) -> str:
    """Generate a single @Parameter property declaration."""
    # Handle entity types
    if param.type == "entity" and param.entity_name:
        swift_type = param.entity_name
        if param.optional:
            swift_type = f"{swift_type}?"
        lines: list[str] = []
        attrs: list[str] = [f'title: "{escape_swift_string(param.description)}"']
        decorator = f"    @Parameter({', '.join(attrs)})"
        lines.append(decorator)
        lines.append(f"    var {param.name}: {swift_type}")
        lines.append("")
        return "\n".join(lines)

    # Handle enum types
    if param.type == "enum" and param.enum_cases:
        # Generate enum type inline or reference it
        swift_type = _generate_enum_type_name(param.name)
        if param.optional:
            swift_type = f"{swift_type}?"
        lines: list[str] = []
        attrs: list[str] = [f'title: "{escape_swift_string(param.description)}"']
        decorator = f"    @Parameter({', '.join(attrs)})"
        lines.append(decorator)
        if param.default is not None:
            default_str = _format_swift_default(param.default, param.type)
            lines.append(f"    var {param.name}: {swift_type} = {default_str}")
        else:
            lines.append(f"    var {param.name}: {swift_type}")
        lines.append("")
        return "\n".join(lines)

    # Standard primitive types
    swift_type = SWIFT_TYPE_MAP.get(param.type, "String")
    if param.optional:
        swift_type = f"{swift_type}?"

    lines: list[str] = []

    # Build @Parameter decorator
    attrs: list[str] = [f'title: "{escape_swift_string(param.description)}"']
    decorator = f"    @Parameter({', '.join(attrs)})"
    lines.append(decorator)

    # Property declaration
    if param.default is not None:
        default_str = _format_swift_default(param.default, param.type)
        lines.append(f"    var {param.name}: {swift_type} = {default_str}")
    else:
        lines.append(f"    var {param.name}: {swift_type}")

    lines.append("")

    return "\n".join(lines)


def _generate_enum_type_name(param_name: str) -> str:
    """Generate a PascalCase enum type name from parameter name."""
    # Convert snake_case to PascalCase
    parts = param_name.split("_")
    return "".join(p.capitalize() for p in parts) + "Option"


def _format_swift_default(value: object, param_type: str) -> str:
    """Format a Python default value as a Swift literal."""
    if isinstance(value, str):
        return f'"{escape_swift_string(value)}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return f'"{escape_swift_string(str(value))}"'


# ── Info.plist Fragment Generator ───────────────────────────────────

def generate_info_plist_fragment(intent: IntentIR) -> str | None:
    """Generate an Info.plist XML fragment, or None if no keys declared."""
    if not intent.info_plist_keys:
        return None

    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- Info.plist fragment generated by Axint for {intent.name}Intent -->",
        "<!-- Merge these keys into your app's Info.plist. -->",
        '<plist version="1.0">',
        "<dict>",
    ]
    for key in intent.info_plist_keys:
        lines.append(f"    <key>{escape_xml(key)}</key>")
        lines.append(f"    <string>TODO: Add description for {escape_xml(key)}</string>")
    lines.append("</dict>")
    lines.append("</plist>")
    lines.append("")

    return "\n".join(lines)


# ── Entitlements Fragment Generator ─────────────────────────────────

def generate_entitlements_fragment(intent: IntentIR) -> str | None:
    """Generate a .entitlements XML fragment, or None if no entitlements declared."""
    if not intent.entitlements:
        return None

    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- Entitlements fragment generated by Axint for {intent.name}Intent -->",
        "<!-- Merge these into your target's .entitlements file. -->",
        "<!-- Note: entitlements requiring typed values (string/array) -->",
        "<!-- need manual adjustment — defaults below are boolean true. -->",
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        "<dict>",
    ]
    for ent in intent.entitlements:
        lines.append(f"    <key>{escape_xml(ent)}</key>")
        lines.append("    <true/>")
    lines.append("</dict>")
    lines.append("</plist>")
    lines.append("")

    return "\n".join(lines)
