/**
 * Generator Edge Case Tests
 *
 * Tests for special characters, NaN/Infinity defaults, all Swift type mappings,
 * and multi-parameter scenarios.
 */

import { describe, it, expect } from "vitest";
import { generateSwift } from "../../src/core/generator.js";
import type { IRIntent, IRParameter } from "../../src/core/types.js";

function makeIntent(overrides: Partial<IRIntent> = {}): IRIntent {
  return {
    name: "TestIntent",
    title: "Test Intent",
    description: "A test intent",
    parameters: [],
    returnType: { kind: "primitive", value: "string" },
    sourceFile: "test.ts",
    ...overrides,
  };
}

describe("generateSwift — default value edge cases", () => {
  it("handles NaN default gracefully (falls back to 0)", () => {
    const swift = generateSwift(
      makeIntent({
        parameters: [
          {
            name: "count",
            type: { kind: "primitive", value: "number" },
            title: "Count",
            description: "A count",
            isOptional: false,
            defaultValue: NaN,
          },
        ],
      })
    );
    expect(swift).toContain("var count: Int = 0");
  });

  it("handles Infinity default gracefully (falls back to 0)", () => {
    const swift = generateSwift(
      makeIntent({
        parameters: [
          {
            name: "limit",
            type: { kind: "primitive", value: "number" },
            title: "Limit",
            description: "A limit",
            isOptional: false,
            defaultValue: Infinity,
          },
        ],
      })
    );
    expect(swift).toContain("var limit: Int = 0");
  });

  it("handles boolean default true", () => {
    const swift = generateSwift(
      makeIntent({
        parameters: [
          {
            name: "enabled",
            type: { kind: "primitive", value: "boolean" },
            title: "Enabled",
            description: "Whether enabled",
            isOptional: false,
            defaultValue: true,
          },
        ],
      })
    );
    expect(swift).toContain("var enabled: Bool = true");
  });

  it("handles boolean default false", () => {
    const swift = generateSwift(
      makeIntent({
        parameters: [
          {
            name: "disabled",
            type: { kind: "primitive", value: "boolean" },
            title: "Disabled",
            description: "Whether disabled",
            isOptional: false,
            defaultValue: false,
          },
        ],
      })
    );
    expect(swift).toContain("var disabled: Bool = false");
  });

  it("handles unknown type defaults via safe fallback", () => {
    const swift = generateSwift(
      makeIntent({
        parameters: [
          {
            name: "data",
            type: { kind: "primitive", value: "string" },
            title: "Data",
            description: "Some data",
            isOptional: false,
            defaultValue: { nested: "object" },
          },
        ],
      })
    );
    // Should not crash — uses String() fallback
    expect(swift).toContain("var data: String =");
  });
});

describe("generateSwift — all Swift type mappings", () => {
  const typeTests: { irType: string; swiftType: string }[] = [
    { irType: "string", swiftType: "String" },
    { irType: "number", swiftType: "Int" },
    { irType: "boolean", swiftType: "Bool" },
    { irType: "date", swiftType: "Date" },
    { irType: "duration", swiftType: "Measurement<UnitDuration>" },
    { irType: "url", swiftType: "URL" },
  ];

  for (const { irType, swiftType } of typeTests) {
    it(`maps ${irType} → ${swiftType}`, () => {
      const param: IRParameter = {
        name: "value",
        type: {
          kind: "primitive",
          value: irType as "string" | "number" | "boolean" | "date" | "duration" | "url",
        },
        title: "Value",
        description: `A ${irType}`,
        isOptional: false,
      };
      const swift = generateSwift(makeIntent({ parameters: [param] }));
      expect(swift).toContain(`var value: ${swiftType}`);
    });
  }
});

describe("generateSwift — structure", () => {
  it("generates correct struct name with Intent suffix", () => {
    const swift = generateSwift(makeIntent({ name: "SendMessage" }));
    expect(swift).toContain("struct SendMessageIntent: AppIntent");
  });

  it("includes the 3 header comment lines", () => {
    const swift = generateSwift(makeIntent({ name: "MyAction" }));
    const lines = swift.split("\n");
    expect(lines[0]).toBe("// MyActionIntent.swift");
    expect(lines[1]).toContain("Generated by Axint");
    expect(lines[2]).toContain("Do not edit manually");
  });

  it("lists available parameters in perform comment", () => {
    const swift = generateSwift(
      makeIntent({
        parameters: [
          {
            name: "name",
            type: { kind: "primitive", value: "string" },
            title: "Name",
            description: "A name",
            isOptional: false,
          },
          {
            name: "age",
            type: { kind: "primitive", value: "number" },
            title: "Age",
            description: "User age",
            isOptional: false,
          },
        ],
      })
    );
    expect(swift).toContain('"name": name');
    expect(swift).toContain('"age": age');
  });

  it("omits param comment when no parameters", () => {
    const swift = generateSwift(makeIntent({ parameters: [] }));
    expect(swift).not.toContain("Available parameters");
  });
});
