export interface FoundationModelsSessionScaffoldInput {
  profileName: string;
  tools?: string[];
  allowPrivateCloudCompute?: boolean;
  samplingSeed?: number;
}

export interface EvaluationsScaffoldInput {
  suiteName: string;
  maxToolCalls?: number;
}

export function generateFoundationModelsSessionScaffold(
  input: FoundationModelsSessionScaffoldInput
): string {
  const profileName = sanitizeSwiftIdentifier(input.profileName || "AxintProfile");
  const tools = input.tools?.map(sanitizeSwiftIdentifier) ?? [];
  const toolList = tools.length > 0 ? tools.map((tool) => `${tool}()`).join(", ") : "";
  const samplingSeed = Number.isInteger(input.samplingSeed) ? input.samplingSeed : 42;
  const privateCloudHelper = input.allowPrivateCloudCompute
    ? [
        ``,
        `    func makePrivateCloudSession() -> LanguageModelSession {`,
        `        let model = PrivateCloudComputeLanguageModel()`,
        `        return LanguageModelSession(model: model) {`,
        `            "Follow the user's request and preserve the same tool-safety policy used on device."`,
        `        }`,
        `    }`,
        ``,
        `    func privateCloudGenerationOptions() -> GenerationOptions {`,
        `        // iOS 27 Beta 3: PCC otherwise uses greedy decoding.`,
        `        GenerationOptions(samplingMode: .randomThreshold(0.95, seed: ${samplingSeed}))`,
        `    }`,
      ]
    : [``, `    // Private Cloud Compute fallback disabled for this scaffold.`];

  return [
    `// ${profileName}.swift`,
    `// Generated by Axint for Foundation Models / Apple Intelligence proof.`,
    `import Foundation`,
    `import FoundationModels`,
    ``,
    `struct ${profileName} {`,
    `    func makeSession() async throws -> LanguageModelSession {`,
    `        let onDeviceModel = SystemLanguageModel.default`,
    `        let tools = [${toolList}]`,
    `        _ = tools`,
    `        return LanguageModelSession(model: onDeviceModel) {`,
    `            "Follow the user's request, avoid unnecessary tool calls, and ask for confirmation before destructive actions."`,
    `        }`,
    `    }`,
    ...privateCloudHelper,
    `}`,
    ``,
  ].join("\n");
}

export function generateEvaluationsScaffold(input: EvaluationsScaffoldInput): string {
  const suiteName = sanitizeSwiftIdentifier(input.suiteName || "AxintEvaluations");
  const maxToolCalls = input.maxToolCalls ?? 3;

  return [
    `// ${suiteName}.swift`,
    `// Generated by Axint for Evaluations proof.`,
    `import Evaluations`,
    `import FoundationModels`,
    ``,
    `struct ${suiteName} {`,
    `    let maxToolCalls = ${maxToolCalls}`,
    ``,
    `    func evaluateToolCallingSafety(transcriptToolCallCount: Int) throws {`,
    `        precondition(transcriptToolCallCount <= maxToolCalls, "Model exceeded the allowed tool-call budget")`,
    `    }`,
    `}`,
    ``,
  ].join("\n");
}

function sanitizeSwiftIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return sanitized || "AxintGenerated";
}
