export interface FoundationModelsSessionScaffoldInput {
  profileName: string;
  tools?: string[];
  allowPrivateCloudCompute?: boolean;
}

export interface EvaluationsScaffoldInput {
  suiteName: string;
  maxToolCalls?: number;
}

export function generateFoundationModelsSessionScaffold(
  input: FoundationModelsSessionScaffoldInput
): string {
  const profileName = sanitizeSwiftIdentifier(input.profileName || "AxintProfile");
  const tools = input.tools?.map(sanitizeSwiftIdentifier) ?? [];
  const toolList = tools.length > 0 ? tools.map((tool) => `${tool}()`).join(", ") : "";
  const modelLine = input.allowPrivateCloudCompute
    ? `let fallbackModel = PrivateCloudComputeLanguageModel()`
    : `// Private Cloud Compute fallback disabled for this scaffold.`;

  return [
    `// ${profileName}.swift`,
    `// Generated by Axint for Foundation Models / Apple Intelligence proof.`,
    `import Foundation`,
    `import FoundationModels`,
    ``,
    `struct ${profileName} {`,
    `    func makeSession() async throws -> LanguageModelSession {`,
    `        #if targetEnvironment(simulator)`,
    `        // iOS 27 Beta 3: verify Private Cloud Compute paths on a physical device.`,
    `        #endif`,
    `        let onDeviceModel = SystemLanguageModel.default`,
    `        ${modelLine}`,
    `        let tools = [${toolList}]`,
    `        _ = tools`,
    `        return LanguageModelSession(model: onDeviceModel) {`,
    `            "Follow the user's request, avoid unnecessary tool calls, and ask for confirmation before destructive actions."`,
    `        }`,
    `    }`,
    `}`,
    ``,
  ].join("\n");
}

export function generateEvaluationsScaffold(input: EvaluationsScaffoldInput): string {
  const suiteName = sanitizeSwiftIdentifier(input.suiteName || "AxintEvaluations");
  const maxToolCalls = input.maxToolCalls ?? 3;

  return [
    `// ${suiteName}.swift`,
    `// Generated by Axint for Evaluations proof.`,
    `import Evaluations`,
    `import FoundationModels`,
    ``,
    `struct ${suiteName} {`,
    `    let maxToolCalls = ${maxToolCalls}`,
    ``,
    `    func evaluateToolCallingSafety(transcriptToolCallCount: Int) throws {`,
    `        precondition(transcriptToolCallCount <= maxToolCalls, "Model exceeded the allowed tool-call budget")`,
    `    }`,
    `}`,
    ``,
  ].join("\n");
}

function sanitizeSwiftIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return sanitized || "AxintGenerated";
}
