/**
 * Axint Swift Code Generator
 *
 * Transforms the IR into clean, idiomatic Swift App Intent source code.
 * Uses string templates for readability and maintainability.
 */

import type { IRIntent, IRParameter, IRType } from "./types.js";
import { irTypeToSwift } from "./types.js";

/**
 * Escape a string for safe interpolation into Swift string literals.
 * Prevents code injection via user-controlled titles/descriptions.
 */
export function escapeSwiftString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Generate a Swift App Intent source file from an IR intent.
 */
export function generateSwift(intent: IRIntent): string {
  const lines: string[] = [];

  // File header
  lines.push(`// ${intent.name}Intent.swift`);
  lines.push(`// Generated by Axint — https://github.com/agenticempire/axint`);
  lines.push(`// Do not edit manually. Re-run \`axint compile\` to regenerate.`);
  lines.push(``);
  lines.push(`import AppIntents`);
  lines.push(``);

  // Struct declaration
  lines.push(`struct ${intent.name}Intent: AppIntent {`);

  // Static metadata
  lines.push(
    `    static let title: LocalizedStringResource = "${escapeSwiftString(intent.title)}"`
  );
  lines.push(
    `    static let description: IntentDescription = IntentDescription("${escapeSwiftString(intent.description)}")`
  );
  lines.push(``);

  // Parameters
  for (const param of intent.parameters) {
    lines.push(generateParameter(param));
  }

  if (intent.parameters.length > 0) {
    lines.push(``);
  }

  // Perform function
  lines.push(`    func perform() async throws -> some IntentResult {`);
  lines.push(`        // TODO: Implement your intent logic here`);

  if (intent.parameters.length > 0) {
    const paramList = intent.parameters.map((p) => `"${p.name}": ${p.name}`).join(", ");
    lines.push(`        // Available parameters: ${paramList}`);
  }

  lines.push(`        return .result()`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

// ─── Helpers ─────────────────────────────────────────────────────────

function generateParameter(param: IRParameter): string {
  const swiftType = irTypeToSwift(param.type);
  const lines: string[] = [];

  // Build @Parameter decorator
  const attrs: string[] = [];
  attrs.push(`title: "${escapeSwiftString(param.title)}"`);
  if (param.description) {
    attrs.push(`description: "${escapeSwiftString(param.description)}"`);
  }

  const decorator = `    @Parameter(${attrs.join(", ")})`;
  lines.push(decorator);

  // Property declaration
  if (param.defaultValue !== undefined) {
    const defaultStr = formatSwiftDefault(param.defaultValue, param.type);
    lines.push(`    var ${param.name}: ${swiftType} = ${defaultStr}`);
  } else {
    lines.push(`    var ${param.name}: ${swiftType}`);
  }

  lines.push(``);

  return lines.join("\n");
}

function formatSwiftDefault(value: unknown, _type: IRType): string {
  if (typeof value === "string") return `"${escapeSwiftString(value)}"`;
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return `0`; // Guard against NaN/Infinity
    return `${value}`;
  }
  if (typeof value === "boolean") return value ? "true" : "false";
  return `"${escapeSwiftString(String(value))}"`; // Safe fallback
}
