/**
 * Axint Swift Code Generator
 *
 * Transforms the IR into clean, idiomatic Swift App Intent source code.
 * Uses string templates for readability and maintainability.
 *
 * In addition to the primary Swift file, this module can emit two
 * companion fragments:
 *   - an Info.plist XML fragment, listing the keys the intent requires
 *   - an .entitlements XML fragment, listing the entitlements the
 *     intent requires
 *
 * Both fragments are designed to be merged into the host Xcode project
 * by the user (or a future axint-link command).
 */

import type { IRIntent, IRParameter, IRType, IREntity } from "./types.js";
import { irTypeToSwift } from "./types.js";

// ─── String Escaping ─────────────────────────────────────────────────

/**
 * Escape a string for safe interpolation into Swift string literals.
 * Prevents code injection via user-controlled titles/descriptions.
 */
export function escapeSwiftString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Escape a string for safe interpolation into XML (Info.plist or
 * .entitlements). Plist XML uses the same rules as general XML.
 */
export function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// ─── Primary Swift Generator ─────────────────────────────────────────

/**
 * Generate a Swift App Intent source file from an IR intent.
 * If entities are present, they are generated first, followed by the intent.
 */
export function generateSwift(intent: IRIntent): string {
  const lines: string[] = [];

  // File header
  lines.push(`// ${intent.name}Intent.swift`);
  lines.push(`// Generated by Axint — https://github.com/agenticempire/axint`);
  lines.push(`// Do not edit manually. Re-run \`axint compile\` to regenerate.`);
  lines.push(``);
  lines.push(`import AppIntents`);
  lines.push(`import Foundation`);
  lines.push(``);

  // Generate entities before the intent
  if (intent.entities && intent.entities.length > 0) {
    for (const entity of intent.entities) {
      lines.push(generateEntity(entity));
      lines.push(``);
      lines.push(generateEntityQuery(entity));
      lines.push(``);
    }
  }

  // Struct declaration
  lines.push(`struct ${intent.name}Intent: AppIntent {`);

  // Static metadata
  lines.push(
    `    static let title: LocalizedStringResource = "${escapeSwiftString(intent.title)}"`
  );
  lines.push(
    `    static let description: IntentDescription = IntentDescription("${escapeSwiftString(intent.description)}")`
  );
  if (intent.isDiscoverable !== undefined) {
    lines.push(`    static let isDiscoverable: Bool = ${intent.isDiscoverable}`);
  }
  lines.push(``);

  // Parameters
  for (const param of intent.parameters) {
    lines.push(generateParameter(param));
  }

  if (intent.parameters.length > 0) {
    lines.push(``);
  }

  // Perform function with return-type aware signature
  const returnTypeSignature = generateReturnSignature(
    intent.returnType,
    intent.customResultType
  );
  lines.push(`    func perform() async throws -> ${returnTypeSignature} {`);
  lines.push(`        // TODO: Implement your intent logic here.`);

  if (intent.parameters.length > 0) {
    const paramList = intent.parameters.map((p) => `\\(${p.name})`).join(", ");
    lines.push(`        // Parameters available: ${paramList}`);
  }

  // Add intent donation if enabled
  if (intent.donateOnPerform) {
    lines.push(`        `);
    lines.push(`        // Donate this intent to Siri and Spotlight`);
    lines.push(`        try? await IntentDonationManager.shared.donate(intent: self)`);
  }

  lines.push(generatePerformReturn(intent.returnType, intent.customResultType));
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

// ─── Entity Generation ───────────────────────────────────────────────

/**
 * Generate an AppEntity struct from an IREntity definition.
 */
export function generateEntity(entity: IREntity): string {
  const lines: string[] = [];
  const propertyNames = new Set(entity.properties.map((p) => p.name));

  lines.push(`struct ${entity.name}: AppEntity {`);
  lines.push(`    typealias DefaultQuery = ${entity.name}Query`);
  lines.push(``);

  // Apple requires AppEntity to have an id property
  const hasId = propertyNames.has("id");
  if (!hasId) {
    lines.push(`    var id: String`);
  }

  // Properties
  for (const prop of entity.properties) {
    const swiftType = irTypeToSwift(prop.type);
    lines.push(`    var ${prop.name}: ${swiftType}`);
  }

  lines.push(``);

  // Type display representation
  lines.push(
    `    static let typeDisplayRepresentation: TypeDisplayRepresentation = TypeDisplayRepresentation(`
  );
  lines.push(
    `        name: LocalizedStringResource("${escapeSwiftString(entity.name)}")`
  );
  lines.push(`    )`);
  lines.push(``);

  // Display representation computed property — title/subtitle are property
  // name references, so we emit Swift string interpolation \(propName)
  lines.push(`    var displayRepresentation: DisplayRepresentation {`);
  lines.push(`        DisplayRepresentation(`);
  lines.push(
    `            title: "\\(${entity.displayRepresentation.title})"${entity.displayRepresentation.subtitle || entity.displayRepresentation.image ? "," : ""}`
  );
  if (entity.displayRepresentation.subtitle) {
    const hasImage = !!entity.displayRepresentation.image;
    lines.push(
      `            subtitle: "\\(${entity.displayRepresentation.subtitle})"${hasImage ? "," : ""}`
    );
  }
  if (entity.displayRepresentation.image) {
    lines.push(
      `            image: .init(systemName: "${escapeSwiftString(entity.displayRepresentation.image)}")`
    );
  }
  lines.push(`        )`);
  lines.push(`    }`);

  lines.push(`}`);

  return lines.join("\n");
}

/**
 * Generate an EntityQuery conformance struct based on the entity's query type.
 */
export function generateEntityQuery(entity: IREntity): string {
  const lines: string[] = [];
  const queryType = entity.queryType;

  lines.push(`struct ${entity.name}Query: EntityQuery {`);
  lines.push(
    `    func entities(for identifiers: [${entity.name}.ID]) async throws -> [${entity.name}] {`
  );
  lines.push(`        // TODO: Fetch entities by IDs`);
  lines.push(`        return []`);
  lines.push(`    }`);
  lines.push(``);

  // Generate appropriate query method based on queryType
  if (queryType === "all") {
    lines.push(`    func allEntities() async throws -> [${entity.name}] {`);
    lines.push(`        // TODO: Return all entities`);
    lines.push(`        return []`);
    lines.push(`    }`);
  } else if (queryType === "id") {
    // ID-based query is handled by entities(for:) above
    lines.push(`    // ID-based query is provided by the entities(for:) method above`);
  } else if (queryType === "string") {
    lines.push(
      `    func entities(matching string: String) async throws -> [${entity.name}] {`
    );
    lines.push(`        // TODO: Search entities by string`);
    lines.push(`        return []`);
    lines.push(`    }`);
  } else if (queryType === "property") {
    // Property-based query requires additional configuration
    lines.push(`    // Property-based query: implement using EntityPropertyQuery`);
    lines.push(`    // Example: property.where { \\$0.status == "active" }`);
  }

  lines.push(`}`);

  return lines.join("\n");
}

// ─── Info.plist Fragment Generator ───────────────────────────────────

/**
 * Generate an Info.plist XML fragment from the intent's declared keys.
 * Returns `undefined` if the intent declares no Info.plist keys.
 *
 * The fragment is a bare `<dict>`-less sequence of `<key>…</key>` /
 * `<string>…</string>` pairs, ready to be merged into an existing
 * Info.plist. A commented header identifies the source intent so users
 * can audit provenance.
 */
export function generateInfoPlistFragment(intent: IRIntent): string | undefined {
  const keys = intent.infoPlistKeys;
  if (!keys || Object.keys(keys).length === 0) return undefined;

  const lines: string[] = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(`<!-- Info.plist fragment generated by Axint for ${intent.name}Intent -->`);
  lines.push(`<!-- Merge these keys into your app's Info.plist. -->`);
  lines.push(`<plist version="1.0">`);
  lines.push(`<dict>`);
  for (const [key, desc] of Object.entries(keys)) {
    lines.push(`    <key>${escapeXml(key)}</key>`);
    lines.push(`    <string>${escapeXml(desc)}</string>`);
  }
  lines.push(`</dict>`);
  lines.push(`</plist>`);
  lines.push(``);

  return lines.join("\n");
}

// ─── Entitlements Fragment Generator ─────────────────────────────────

/**
 * Generate a `.entitlements` XML fragment from the intent's declared
 * entitlements. Returns `undefined` if the intent declares none.
 *
 * Axint only knows the entitlement identifiers, so all entries are
 * emitted as `<true/>` boolean entitlements. If an entitlement requires
 * a typed value (string, array), users must edit the fragment after
 * generation — a TODO comment is emitted to flag this.
 */
export function generateEntitlementsFragment(intent: IRIntent): string | undefined {
  const ents = intent.entitlements;
  if (!ents || ents.length === 0) return undefined;

  const lines: string[] = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(
    `<!-- Entitlements fragment generated by Axint for ${intent.name}Intent -->`
  );
  lines.push(`<!-- Merge these into your target's .entitlements file. -->`);
  lines.push(`<!-- Note: entitlements requiring typed values (string/array) -->`);
  lines.push(`<!-- need manual adjustment — defaults below are boolean true. -->`);
  lines.push(
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`
  );
  lines.push(`<plist version="1.0">`);
  lines.push(`<dict>`);
  for (const ent of ents) {
    lines.push(`    <key>${escapeXml(ent)}</key>`);
    lines.push(`    <true/>`);
  }
  lines.push(`</dict>`);
  lines.push(`</plist>`);
  lines.push(``);

  return lines.join("\n");
}

// ─── Helpers ─────────────────────────────────────────────────────────

function generateParameter(param: IRParameter): string {
  const swiftType = irTypeToSwift(param.type);
  const lines: string[] = [];

  // Build @Parameter decorator
  const attrs: string[] = [];
  attrs.push(`title: "${escapeSwiftString(param.title)}"`);
  if (param.description) {
    attrs.push(`description: "${escapeSwiftString(param.description)}"`);
  }

  const decorator = `    @Parameter(${attrs.join(", ")})`;
  lines.push(decorator);

  // Property declaration
  if (param.defaultValue !== undefined) {
    const defaultStr = formatSwiftDefault(param.defaultValue, param.type);
    lines.push(`    var ${param.name}: ${swiftType} = ${defaultStr}`);
  } else {
    lines.push(`    var ${param.name}: ${swiftType}`);
  }

  lines.push(``);

  return lines.join("\n");
}

/**
 * Choose the Swift return-type signature for the generated perform().
 * We map the inferred IR return type to an App Intents `IntentResult`
 * shape. For primitive return types we use `some ReturnsValue<T>`;
 * for custom result types we use the custom type; otherwise we fall
 * back to `some IntentResult`.
 */
function generateReturnSignature(type: IRType, customResultType?: string): string {
  if (customResultType) {
    return customResultType;
  }
  if (type.kind === "primitive") {
    const swift = irTypeToSwift(type);
    return `some IntentResult & ReturnsValue<${swift}>`;
  }
  if (type.kind === "optional" && type.innerType.kind === "primitive") {
    const swift = irTypeToSwift(type.innerType);
    return `some IntentResult & ReturnsValue<${swift}>`;
  }
  return `some IntentResult`;
}

/**
 * Emit the `return .result(...)` line that matches the return signature
 * produced by `generateReturnSignature`. When the return type is a
 * primitive we return a well-typed default placeholder the user can
 * replace; otherwise we emit a plain `.result()`.
 */
function generatePerformReturn(type: IRType, customResultType?: string): string {
  const indent = "        ";
  if (customResultType) {
    // For custom result types, the user must provide the implementation
    return `${indent}// TODO: Return a ${customResultType} instance`;
  }
  if (type.kind === "primitive") {
    return `${indent}return .result(value: ${defaultLiteralFor(type.value)})`;
  }
  if (type.kind === "optional" && type.innerType.kind === "primitive") {
    return `${indent}return .result(value: ${defaultLiteralFor(type.innerType.value)})`;
  }
  return `${indent}return .result()`;
}

function defaultLiteralFor(primitive: string): string {
  switch (primitive) {
    case "string":
      return `""`;
    case "int":
      return `0`;
    case "double":
      return `0.0`;
    case "float":
      return `Float(0)`;
    case "boolean":
      return `false`;
    case "date":
      return `Date()`;
    case "duration":
      return `Measurement<UnitDuration>(value: 0, unit: .seconds)`;
    case "url":
      return `URL(string: "about:blank")!`;
    default:
      return `""`;
  }
}

function formatSwiftDefault(value: unknown, _type: IRType): string {
  if (typeof value === "string") return `"${escapeSwiftString(value)}"`;
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return `0`; // Guard against NaN/Infinity
    return `${value}`;
  }
  if (typeof value === "boolean") return value ? "true" : "false";
  return `"${escapeSwiftString(String(value))}"`; // Safe fallback
}
