/**
 * Axint SwiftUI View Generator
 *
 * Transforms IRView into clean, idiomatic SwiftUI source code.
 * Follows the same string-template approach as the intent generator
 * for consistency and readability.
 */

import type { IRView, IRViewProp, IRViewState, ViewBodyNode } from "./types.js";
import { irTypeToSwift } from "./types.js";
import { escapeSwiftString } from "./generator.js";

/**
 * Generate a SwiftUI view source file from an IRView.
 */
export function generateSwiftUIView(view: IRView): string {
  const lines: string[] = [];

  lines.push(`// ${view.name}.swift`);
  lines.push(`// Generated by Axint — https://github.com/agenticempire/axint`);
  lines.push(`// Do not edit manually. Re-run \`axint compile\` to regenerate.`);
  lines.push(``);
  lines.push(`import SwiftUI`);
  lines.push(``);

  lines.push(`struct ${view.name}: View {`);

  // Props (let bindings from parent)
  for (const p of view.props) {
    const swift = irTypeToSwift(p.type);
    const decl = p.isOptional ? `${swift}?` : swift;
    if (p.defaultValue !== undefined) {
      lines.push(`    var ${p.name}: ${decl} = ${formatLiteral(p.defaultValue, p.type)}`);
    } else {
      lines.push(`    var ${p.name}: ${decl}`);
    }
  }

  if (view.props.length > 0 && view.state.length > 0) {
    lines.push(``);
  }

  // State properties
  for (const s of view.state) {
    lines.push(generateStateProperty(s));
  }

  if (view.props.length > 0 || view.state.length > 0) {
    lines.push(``);
  }

  // Body
  lines.push(`    var body: some View {`);
  for (const node of view.body) {
    const nodeLines = generateBodyNode(node, 2);
    lines.push(...nodeLines);
  }
  lines.push(`    }`);

  lines.push(`}`);
  lines.push(``);

  // Preview
  lines.push(`#Preview {`);
  if (view.props.length > 0) {
    const previewArgs = view.props
      .filter((p) => !p.isOptional && p.defaultValue === undefined)
      .map((p) => `${p.name}: ${previewDefault(p)}`)
      .join(", ");
    lines.push(`    ${view.name}(${previewArgs})`);
  } else {
    lines.push(`    ${view.name}()`);
  }
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function generateStateProperty(s: IRViewState): string {
  const swift = irTypeToSwift(s.type);

  switch (s.kind) {
    case "binding":
      return `    @Binding var ${s.name}: ${swift}`;
    case "environment":
      return `    @Environment(${s.environmentKey ?? `\\.${s.name}`}) var ${s.name}`;
    case "observed":
      return `    @ObservedObject var ${s.name}: ${swift}`;
    case "state":
    default: {
      if (s.defaultValue !== undefined) {
        return `    @State private var ${s.name}: ${swift} = ${formatLiteral(s.defaultValue, s.type)}`;
      }
      return `    @State private var ${s.name}: ${swift}`;
    }
  }
}

function generateBodyNode(node: ViewBodyNode, depth: number): string[] {
  const indent = "    ".repeat(depth);
  const lines: string[] = [];

  switch (node.kind) {
    case "text":
      lines.push(`${indent}Text("${escapeSwiftString(node.content)}")`);
      break;

    case "image":
      if (node.systemName) {
        lines.push(`${indent}Image(systemName: "${escapeSwiftString(node.systemName)}")`);
      } else if (node.name) {
        lines.push(`${indent}Image("${escapeSwiftString(node.name)}")`);
      }
      break;

    case "button":
      if (node.action) {
        lines.push(`${indent}Button("${escapeSwiftString(node.label)}") {`);
        lines.push(`${indent}    ${node.action}`);
        lines.push(`${indent}}`);
      } else {
        lines.push(`${indent}Button("${escapeSwiftString(node.label)}") { }`);
      }
      break;

    case "spacer":
      lines.push(`${indent}Spacer()`);
      break;

    case "divider":
      lines.push(`${indent}Divider()`);
      break;

    case "vstack":
    case "hstack":
    case "zstack": {
      const container =
        node.kind === "vstack" ? "VStack" : node.kind === "hstack" ? "HStack" : "ZStack";
      const args: string[] = [];
      if ("alignment" in node && node.alignment)
        args.push(`alignment: .${node.alignment}`);
      if ("spacing" in node && node.spacing !== undefined)
        args.push(`spacing: ${node.spacing}`);
      const argStr = args.length > 0 ? `(${args.join(", ")})` : "";

      lines.push(`${indent}${container}${argStr} {`);
      for (const child of node.children) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;
    }

    case "foreach":
      lines.push(
        `${indent}ForEach(${node.collection}, id: \\.self) { ${node.itemName} in`
      );
      for (const child of node.body) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;

    case "conditional":
      lines.push(`${indent}if ${node.condition} {`);
      for (const child of node.then) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      if (node.else && node.else.length > 0) {
        lines.push(`${indent}} else {`);
        for (const child of node.else) {
          lines.push(...generateBodyNode(child, depth + 1));
        }
      }
      lines.push(`${indent}}`);
      break;

    case "navigationLink":
      lines.push(`${indent}NavigationLink(destination: ${node.destination}()) {`);
      for (const child of node.label) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;

    case "list":
      lines.push(`${indent}List {`);
      for (const child of node.children) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;

    case "raw":
      lines.push(`${indent}${node.swift}`);
      break;
  }

  return lines;
}

function formatLiteral(value: unknown, _type: { kind: string }): string {
  if (typeof value === "string") return `"${escapeSwiftString(value)}"`;
  if (typeof value === "number") return `${value}`;
  if (typeof value === "boolean") return value ? "true" : "false";
  return `"${escapeSwiftString(String(value))}"`;
}

function previewDefault(p: IRViewProp): string {
  if (p.type.kind === "primitive") {
    switch (p.type.value) {
      case "string":
        return `"Preview"`;
      case "int":
        return `0`;
      case "double":
        return `0.0`;
      case "float":
        return `Float(0)`;
      case "boolean":
        return `false`;
      case "date":
        return `Date()`;
      case "url":
        return `URL(string: "https://example.com")!`;
      default:
        return `""`;
    }
  }
  return `""`;
}
