/**
 * Axint WidgetKit Widget Generator
 *
 * Transforms IRWidget into clean, idiomatic Swift WidgetKit source code.
 * Generates TimelineEntry, TimelineProvider, Widget struct, and Preview.
 */

import type { IRWidget, IRType, ViewBodyNode } from "./types.js";
import { irTypeToSwift } from "./types.js";
import { escapeSwiftString } from "./generator.js";

/**
 * Generate a WidgetKit widget source file from an IRWidget.
 */
export function generateSwiftWidget(widget: IRWidget): string {
  const lines: string[] = [];

  lines.push(`// ${widget.name}Widget.swift`);
  lines.push(`// Generated by Axint — https://github.com/agenticempire/axint`);
  lines.push(`// Do not edit manually. Re-run \`axint compile\` to regenerate.`);
  lines.push(``);
  lines.push(`import WidgetKit`);
  lines.push(`import SwiftUI`);
  lines.push(``);

  // Timeline entry struct
  lines.push(`struct ${widget.name}Entry: TimelineEntry {`);
  lines.push(`    let date: Date`);
  for (const entry of widget.entry) {
    const swift = irTypeToSwift(entry.type);
    if (entry.defaultValue !== undefined) {
      lines.push(
        `    let ${entry.name}: ${swift} = ${formatLiteral(entry.defaultValue, entry.type)}`
      );
    } else {
      lines.push(`    let ${entry.name}: ${swift}`);
    }
  }
  lines.push(`}`);
  lines.push(``);

  // Timeline provider
  lines.push(`struct ${widget.name}Provider: TimelineProvider {`);
  lines.push(`    func placeholder(in context: Context) -> ${widget.name}Entry {`);
  const placeholderFields = widget.entry
    .map((e) => `${e.name}: ${getDefaultValue(e.defaultValue, e.type)}`)
    .join(", ");
  lines.push(
    `        ${widget.name}Entry(date: Date()${placeholderFields ? ", " + placeholderFields : ""})`
  );
  lines.push(`    }`);
  lines.push(``);

  lines.push(
    `    func getSnapshot(in context: Context, completion: @escaping (${widget.name}Entry) -> Void) {`
  );
  lines.push(
    `        let entry = ${widget.name}Entry(date: Date()${placeholderFields ? ", " + placeholderFields : ""})`
  );
  lines.push(`        completion(entry)`);
  lines.push(`    }`);
  lines.push(``);

  lines.push(
    `    func getTimeline(in context: Context, completion: @escaping (Timeline<${widget.name}Entry>) -> Void) {`
  );
  lines.push(
    `        let entry = ${widget.name}Entry(date: Date()${placeholderFields ? ", " + placeholderFields : ""})`
  );

  // Refresh policy
  let nextRefresh: string;
  if (widget.refreshPolicy === "never") {
    nextRefresh = "Calendar.current.date(byAdding: .day, value: 365, to: Date())!";
  } else if (widget.refreshPolicy === "after" && widget.refreshInterval) {
    nextRefresh = `Calendar.current.date(byAdding: .minute, value: ${widget.refreshInterval}, to: Date())!`;
  } else {
    nextRefresh = `Calendar.current.date(byAdding: .hour, value: 1, to: Date())!`;
  }

  lines.push(
    `        let timeline = Timeline(entries: [entry], policy: .after(${nextRefresh}))`
  );
  lines.push(`        completion(timeline)`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  // Widget view
  lines.push(`struct ${widget.name}EntryView: View {`);
  lines.push(`    var entry: ${widget.name}Provider.Entry`);
  lines.push(``);
  lines.push(`    var body: some View {`);
  for (const node of widget.body) {
    const nodeLines = generateBodyNode(node, 2);
    lines.push(...nodeLines);
  }
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  // Widget struct
  lines.push(`struct ${widget.name}Widget: Widget {`);
  lines.push(`    let kind: String = "${widget.name}"`);
  lines.push(``);
  lines.push(`    var body: some WidgetConfiguration {`);
  lines.push(`        StaticConfiguration(`);
  lines.push(`            kind: kind,`);
  lines.push(`            provider: ${widget.name}Provider()`);
  lines.push(`        ) { entry in`);
  lines.push(`            ${widget.name}EntryView(entry: entry)`);
  lines.push(`        }`);
  lines.push(
    `        .configurationDisplayName("${escapeSwiftString(widget.displayName)}")`
  );
  lines.push(`        .description("${escapeSwiftString(widget.description)}")`);
  lines.push(`        .supportedFamilies(${familiesArray(widget.families)})`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  // Preview
  lines.push(`#Preview(as: .systemSmall) {`);
  lines.push(`    ${widget.name}Widget()`);
  lines.push(`} timeline: {`);
  const previewEntry = widget.entry
    .map((e) => `${e.name}: ${getDefaultValue(e.defaultValue, e.type)}`)
    .join(", ");
  lines.push(
    `    ${widget.name}Entry(date: Date()${previewEntry ? ", " + previewEntry : ""})`
  );
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

// ─── Helpers ────────────────────────────────────────────────────────

function familiesArray(families: string[]): string {
  const mapped = families.map((f) => `.${f}`);
  return `[${mapped.join(", ")}]`;
}

function formatLiteral(value: unknown, _type?: IRType): string {
  if (typeof value === "string") {
    return `"${escapeSwiftString(value)}"`;
  }
  if (typeof value === "number") {
    return String(value);
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (value === null) {
    return "nil";
  }
  if (Array.isArray(value)) {
    const elements = value.map((v) => formatLiteral(v));
    return `[${elements.join(", ")}]`;
  }
  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `"${escapeSwiftString(k)}": ${formatLiteral(v)}`
    );
    return `[${entries.join(", ")}]`;
  }
  return "nil";
}

function getDefaultValue(value: unknown, type?: IRType): string {
  if (value !== undefined) {
    return formatLiteral(value, type);
  }
  if (!type) return `nil`;
  if (type.kind === "array") return `[]`;
  if (type.kind === "optional") return `nil`;
  const swift = irTypeToSwift(type);
  if (swift === "String") return `""`;
  if (swift === "Int") return `0`;
  if (swift === "Double" || swift === "Float") return `0.0`;
  if (swift === "Bool") return `false`;
  if (swift === "Date") return `Date()`;
  if (swift === "URL") return `URL(string: "https://example.com")!`;
  return `nil`;
}

function generateBodyNode(node: ViewBodyNode, depth: number): string[] {
  const indent = "    ".repeat(depth);
  const lines: string[] = [];

  switch (node.kind) {
    case "text":
      lines.push(`${indent}Text("${escapeSwiftString(node.content)}")`);
      break;

    case "image":
      if (node.systemName) {
        lines.push(`${indent}Image(systemName: "${escapeSwiftString(node.systemName)}")`);
      } else if (node.name) {
        lines.push(`${indent}Image("${escapeSwiftString(node.name)}")`);
      }
      break;

    case "button":
      if (node.action) {
        lines.push(`${indent}Button("${escapeSwiftString(node.label)}") {`);
        lines.push(`${indent}    ${node.action}`);
        lines.push(`${indent}}`);
      } else {
        lines.push(`${indent}Button("${escapeSwiftString(node.label)}") { }`);
      }
      break;

    case "spacer":
      lines.push(`${indent}Spacer()`);
      break;

    case "divider":
      lines.push(`${indent}Divider()`);
      break;

    case "vstack":
    case "hstack":
    case "zstack": {
      const container =
        node.kind === "vstack" ? "VStack" : node.kind === "hstack" ? "HStack" : "ZStack";
      const args: string[] = [];
      if ("alignment" in node && node.alignment)
        args.push(`alignment: .${node.alignment}`);
      if ("spacing" in node && node.spacing !== undefined)
        args.push(`spacing: ${node.spacing}`);
      const argStr = args.length > 0 ? `(${args.join(", ")})` : "";

      lines.push(`${indent}${container}${argStr} {`);
      for (const child of node.children) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;
    }

    case "foreach":
      lines.push(
        `${indent}ForEach(${node.collection}, id: \\.self) { ${node.itemName} in`
      );
      for (const child of node.body) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;

    case "conditional":
      lines.push(`${indent}if ${node.condition} {`);
      for (const child of node.then) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      if (node.else && node.else.length > 0) {
        lines.push(`${indent}} else {`);
        for (const child of node.else) {
          lines.push(...generateBodyNode(child, depth + 1));
        }
      }
      lines.push(`${indent}}`);
      break;

    case "navigationLink":
      lines.push(`${indent}NavigationLink(destination: ${node.destination}()) {`);
      for (const child of node.label) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;

    case "list":
      lines.push(`${indent}List {`);
      for (const child of node.children) {
        lines.push(...generateBodyNode(child, depth + 1));
      }
      lines.push(`${indent}}`);
      break;

    case "raw":
      lines.push(`${indent}${node.swift}`);
      break;
  }

  return lines;
}
