export interface AppIntentsTestingHarnessInput {
  swiftSource: string;
  moduleName?: string;
  bundleIdentifier?: string;
  fileName?: string;
}

export function generateAppIntentsTestingHarness(
  input: AppIntentsTestingHarnessInput
): string {
  const moduleName = sanitizeSwiftIdentifier(input.moduleName ?? "YourApp");
  const bundleIdentifier = escapeSwiftString(
    input.bundleIdentifier ?? input.moduleName ?? "com.example.YourApp"
  );
  const intents = uniqueMatches(
    input.swiftSource,
    /\bstruct\s+(\w+Intent)\s*:[^{\n]*\bAppIntent\b/g
  );
  const entities = uniqueMatches(
    input.swiftSource,
    /\bstruct\s+(\w+)\s*:[^{\n]*\bAppEntity\b/g
  );
  const sourceLabel = input.fileName ? ` for ${input.fileName}` : "";

  return [
    `// Generated by Axint${sourceLabel}.`,
    "// Add this file to an XCUITest bundle signed with the same team as the app.",
    "import Testing",
    "#if canImport(AppIntents)",
    "import AppIntents",
    "#endif",
    "#if canImport(AppIntentsTesting)",
    "import AppIntentsTesting",
    "#endif",
    `@testable import ${moduleName}`,
    "",
    '@Suite("Axint App Intents readiness")',
    "struct AxintAppIntentsReadinessTests {",
    renderDefinitions(bundleIdentifier),
    ...renderIntentTests(intents),
    ...renderEntityTests(entities),
    renderReadinessChecklist(intents, entities),
    "}",
    "",
  ].join("\n");
}

function renderDefinitions(bundleIdentifier: string): string {
  return [
    "    private func intentDefinitions() -> IntentDefinitions {",
    `        IntentDefinitions(bundleIdentifier: "${bundleIdentifier}")`,
    "    }",
    "",
  ].join("\n");
}

function renderIntentTests(intents: string[]): string[] {
  if (intents.length === 0) {
    return [
      '    @Test("App Intent metadata checklist")',
      "    func appIntentMetadataChecklist() async throws {",
      "        // AppIntentsTesting: invoke each App Intent with valid, missing, and denial-path parameters.",
      "        // Shortcuts: verify the intent appears with the expected title, description, and parameters.",
      "        #expect(true)",
      "    }",
      "",
    ];
  }

  return intents.flatMap((intent) => [
    `    @Test("${intent} executes through AppIntentsTesting")`,
    `    func ${lowerFirst(intent)}Execution() async throws {`,
    `        let definitions = intentDefinitions()`,
    `        let intentDefinition = definitions.intents["${intent}"]`,
    `        let result = try await intentDefinition.makeIntent().run()`,
    `        #expect(String(describing: result).isEmpty == false)`,
    "    }",
    "",
  ]);
}

function renderEntityTests(entities: string[]): string[] {
  if (entities.length === 0) {
    return [
      '    @Test("App Entity continuity checklist")',
      "    func appEntityContinuityChecklist() async throws {",
      "        // Spotlight: verify indexed entities can be restored by stable id.",
      "        // View annotations: verify visible rows/details attach .appEntityIdentifier(...).",
      "        #expect(true)",
      "    }",
      "",
    ];
  }

  return entities.flatMap((entity) => [
    `    @Test("${entity} resolves through AppIntentsTesting entity APIs")`,
    `    func ${lowerFirst(entity)}Continuity() async throws {`,
    `        let definitions = intentDefinitions()`,
    `        let entityDefinition = definitions.entities["${entity}"]`,
    `        let suggested = try await entityDefinition.suggestedEntities()`,
    `        #expect(suggested.count >= 0)`,
    `        // Spotlight: after mutating ${entity}, assert indexed search can find its stable id.`,
    "        // View annotations: navigate with XCUI, then call viewAnnotations() and assert the visible entity.",
    "    }",
    "",
  ]);
}

function renderReadinessChecklist(intents: string[], entities: string[]): string {
  const intentList = intents.length > 0 ? intents.join(", ") : "your App Intents";
  const entityList = entities.length > 0 ? entities.join(", ") : "your App Entities";
  return [
    '    @Test("Siri, Shortcuts, Spotlight, and view annotation readiness")',
    "    func siriAppSchemaIntegrationChecklist() async throws {",
    `        // Intents under test: ${intentList}.`,
    `        // Entities under test: ${entityList}.`,
    "        let definitions = intentDefinitions()",
    "        #expect(definitions.intents.count >= 0)",
    "        #expect(definitions.entities.count >= 0)",
    "        // AppIntentsTesting: prove Siri/App Schema parameter resolution and confirmation paths with makeIntent(...).run().",
    "        // Shortcuts: run the same action through Shortcuts for conversational edit flows.",
    "        // Spotlight: prove indexed/syncable entity ids survive reindex and device sync.",
    "        // SwiftUI: prove entity rows/details expose .appEntityIdentifier(...) or matching view annotations.",
    "    }",
  ].join("\n");
}

function uniqueMatches(source: string, regex: RegExp): string[] {
  const matches = [...source.matchAll(regex)].map((match) => match[1]).filter(Boolean);
  return [...new Set(matches)];
}

function sanitizeSwiftIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return sanitized || "YourApp";
}

function escapeSwiftString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function lowerFirst(value: string): string {
  return `${value.charAt(0).toLowerCase()}${value.slice(1)}`;
}
