export interface AppIntentsTestingHarnessInput {
  swiftSource: string;
  moduleName?: string;
  fileName?: string;
}

export function generateAppIntentsTestingHarness(
  input: AppIntentsTestingHarnessInput
): string {
  const moduleName = sanitizeSwiftIdentifier(input.moduleName ?? "YourApp");
  const intents = uniqueMatches(
    input.swiftSource,
    /\bstruct\s+(\w+Intent)\s*:[^{\n]*\bAppIntent\b/g
  );
  const entities = uniqueMatches(
    input.swiftSource,
    /\bstruct\s+(\w+)\s*:[^{\n]*\bAppEntity\b/g
  );
  const sourceLabel = input.fileName ? ` for ${input.fileName}` : "";

  return [
    `// Generated by Axint${sourceLabel}.`,
    "// Keep this scaffold in your app test target and replace checklist comments",
    "// with concrete AppIntentsTesting invocations as your Xcode SDK allows.",
    "import Testing",
    "#if canImport(AppIntents)",
    "import AppIntents",
    "#endif",
    "#if canImport(AppIntentsTesting)",
    "import AppIntentsTesting",
    "#endif",
    `@testable import ${moduleName}`,
    "",
    '@Suite("Axint App Intents readiness")',
    "struct AxintAppIntentsReadinessTests {",
    ...renderIntentTests(intents),
    ...renderEntityTests(entities),
    renderReadinessChecklist(intents, entities),
    "}",
    "",
  ].join("\n");
}

function renderIntentTests(intents: string[]): string[] {
  if (intents.length === 0) {
    return [
      '    @Test("App Intent metadata checklist")',
      "    func appIntentMetadataChecklist() async throws {",
      "        // AppIntentsTesting: invoke each App Intent with valid, missing, and denial-path parameters.",
      "        // Shortcuts: verify the intent appears with the expected title, description, and parameters.",
      "        #expect(true)",
      "    }",
      "",
    ];
  }

  return intents.flatMap((intent) => [
    `    @Test("${intent} exposes App Intent metadata")`,
    `    func ${lowerFirst(intent)}Metadata() async throws {`,
    `        // AppIntentsTesting: invoke ${intent} and assert the success, confirmation, and error paths.`,
    `        #expect(String(describing: ${intent}.title).isEmpty == false)`,
    "    }",
    "",
  ]);
}

function renderEntityTests(entities: string[]): string[] {
  if (entities.length === 0) {
    return [
      '    @Test("App Entity continuity checklist")',
      "    func appEntityContinuityChecklist() async throws {",
      "        // Spotlight: verify indexed entities can be restored by stable id.",
      "        // View annotations: verify visible rows/details attach .appEntityIdentifier(...).",
      "        #expect(true)",
      "    }",
      "",
    ];
  }

  return entities.flatMap((entity) => [
    `    @Test("${entity} has stable Siri and Spotlight identity")`,
    `    func ${lowerFirst(entity)}Continuity() async throws {`,
    `        // Spotlight: rehydrate ${entity} by id through its query before and after app relaunch.`,
    "        // View annotations: attach .appEntityIdentifier(...) to SwiftUI rows/details that display this entity.",
    "        #expect(true)",
    "    }",
    "",
  ]);
}

function renderReadinessChecklist(intents: string[], entities: string[]): string {
  const intentList = intents.length > 0 ? intents.join(", ") : "your App Intents";
  const entityList = entities.length > 0 ? entities.join(", ") : "your App Entities";
  return [
    '    @Test("Siri, Shortcuts, Spotlight, and view annotation readiness")',
    "    func siriAppSchemaIntegrationChecklist() async throws {",
    `        // Intents under test: ${intentList}.`,
    `        // Entities under test: ${entityList}.`,
    "        // AppIntentsTesting: prove Siri/App Schema parameter resolution and confirmation paths.",
    "        // Shortcuts: run the same action through Shortcuts, including Use Model transcript grounding.",
    "        // Spotlight: prove indexed/syncable entity ids survive reindex and device sync.",
    "        // SwiftUI: prove entity rows/details expose .appEntityIdentifier(...) or matching UserActivity annotations.",
    "        #expect(true)",
    "    }",
  ].join("\n");
}

function uniqueMatches(source: string, regex: RegExp): string[] {
  const matches = [...source.matchAll(regex)].map((match) => match[1]).filter(Boolean);
  return [...new Set(matches)];
}

function sanitizeSwiftIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return sanitized || "YourApp";
}

function lowerFirst(value: string): string {
  return `${value.charAt(0).toLowerCase()}${value.slice(1)}`;
}
